export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{
        margin: 0,
        padding: 0,
        fontFamily: '"Google Sans", "Roboto", -apple-system, BlinkMacSystemFont, sans-serif',
        backgroundColor: '#f8f9fa',
        overflowX: 'auto' // Allow horizontal scroll when needed
      }}>
        {children}
      </body>
    </html>
  )
}
